### ISSUE TITLE
using RGBD data as input 

### ISSUE THREAD

**Issue by Changliu52** [google-research/robotics_transformer#7]
Amazing work!
I wonder if it is possible to input RGBD data instead of RGB? 
Hopefully with the extra depth information, we can train it with better accuracy.

**Comment by keerthanpg** [comment]
Yes, adding extra channel works off the bat.

**Comment by oym1994** [comment]
Me, too. Why not use the depth data? The depth camera is a very common sensor in robot manipultaiton task. 
Keep waiting for your kind response!
